# -*- coding: utf-8 -*-
"""1302-Assignment1b

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1So1M2lQuOWMAQ5FivQsaNSpxRdZUmaLK
"""

''' 
iolo jones, 1302 PRINC OF PROG FOR DATA SCI II
iolojones41@student.gsu.edu

2) Consider the following string: nums = '10,20,30,40,50'

Create a Python script that creates a list of integers from the string.

The resulting list will be: [10, 20, 30, 40, 50] '''

print("Please enter a string:")
nums = input(int())
print(type(nums))
nums_list = nums.split(',')
integers = map(int, nums_list)
ints = list(integers)
print("The string as a list of integers is:",ints)
for x in ints:
  print("Element:",x,"Type:",type(x))
print(type(nums_list))
