# -*- coding: utf-8 -*-
"""1302-Assignment1a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mNYbpkidhbo1RjdYDZ2tHADJWVjZAQG_
"""

''' 1) Create a Python script that asks the user for a number and then prints out a list of all the divisors of each number less than the asked number. '''

print("Please enter a positive integer:")
number = int(input())
dividers = []
i = 1
if number == 1:
    print("1 is only divisible by itself.")
elif number == 0:
    print("0 may be divided by any number.")
elif number > 1:
    while i < number:
      i += 1
      if number % i == 0:
          dividers.append(i)
    print("The divisors are: ", dividers)
else :
  if number < 0:
    print("Please start again and enter a positive number.")