# -*- coding: utf-8 -*-
"""chatgui.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gvg1-PuETvlBna4JPUNXJmU0FfcuwRGw
"""

import tkinter
from tkinter import *

def send():
    msg = EntryBox.get("1.0",'end-1c').strip()
    EntryBox.delete("0.0",END)

    if msg != '':
        ChatLog.config(state=NORMAL)
        ChatLog.insert(END, "You: " + msg + '\n\n')
        ChatLog.config(foreground="#442265", font=("Verdana", 12 ))

        res = chatbot_response(msg)
        ChatLog.insert(END, "Bot: " + res + '\n\n')

        ChatLog.config(state=DISABLED)
        ChatLog.yview(END)

base = Tk() # create an instance of tkinter frame
base.title("Hello") # base title
base.geometry("400x500") # size of the chat box
base.resizable(width=FALSE, height=FALSE) # fixed size 

ChatLog = Text(base, bd=0, bg="white", height="8", width="50", font="Arial",) # for the chat window

ChatLog.config(state = DISABLED) # change tkinter button state

scrollbar = Scrollbar(base, command=ChatLog.yview, cursor="heart") # connecting the scroll bar to the chat window
ChatLog['yscrollcommand'] = scrollbar.set

SendButton = Button(base, font=("Verdana",12,'bold'), text="Send", width="12", height=5,
                    bd=0, bg="#32de97", activebackground="#3c9d9b",fg='#ffffff',
                    command= send ) # creating a button to enable sending

EntryBox = Text(base, bd=0, bg="white",width="29", height="5", font="Arial") # message entry box
#EntryBox.bind("<Return>", send)

# putting all parts onto the interface
scrollbar.place(x=376,y=6, height=386)
ChatLog.place(x=6,y=6, height=386, width=370)
EntryBox.place(x=128, y=401, height=90, width=265)
SendButton.place(x=6, y=401, height=90)

base.mainloop()