# -*- coding: utf-8 -*-
"""Coding_Lab3_IoloJones

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zOeO4u3ePROU5Rn5eZZRDOfF2y-HlH72
"""

import numpy as np 
from scipy import stats
'''
Iolo Jones  - Coding lab 3
Instructions (90 points) 
In this lab you will be creating a class called GradeStatistics. 
This class would be able to take in a Numpy array of floating point values between [0-100] 
of any length where each element in the array represents the individual assignment grade of 
an student in a class for one assignment (ie, class grade for Homework 1) GradeStatistics 
should method contain and implement the following methods: 
• mean 
• median 
• mode (you may apply a floor or rounding function to it to allow for groupings) 
• standard deviation 
• variance 
'''
class GradeStatistics:
 
    def __init__(self,n): # initialise the class
        self.n = n 
    
    def mean(self): # method to get the mean of the array
        np.mean(self.n) # get the mean of the array
        mean_score = (np.mean(self.n)) 
        return str(round(mean_score,2)) # return the mean rounded to 2 dp

    def median(self): # method to get the median of the array
        return str(round(np.median(self.n),2)) # return the median of the array rounded to 2 dp
    
    def mode(self): # method for the mode
        rounded = [] # create an empy list to store the rounded figures
        for i in range(len(arr)): # iterate through the entire array
          a = round(arr[i]) # round a[0],...,a[n] and assign the rounded number to a variable a_0,...,a_n
          rounded.append(a) # add the rounded number to the list 'rounded'
          mode = stats.mode(rounded) # find the mode of the rounded list
        return mode[0] # return the mode

    def standard_deviation(self): # method for the standard deviation of the array
        return str(round((np.std(self.n)),2)) # return the st dev rounded to 2 dp

    def variance(self): # method to get the variance of the array
        return str(round(np.var(self.n),2)) # return the variance rounded to 2dp
        

arrayy = np.random.uniform(low=0, high=100, size=(50,)) # get 50 random numbers between 0 and 100
arr = np.array(arrayy) # put the 50 numbers into an array
print(arr) # print the numpy array with the 50 randomly generated numbers
gradebook = GradeStatistics(arr) # create the gradebook to hold the scores

print("The mean is:",gradebook.mean()) # calling the method that gets the mean
print("The median is:",gradebook.median()) # calling the method that gets the median
print("The mode is:",gradebook.mode()) # calling the method that gets the mode
print("The standard deviation is:",gradebook.standard_deviation()) # calling the method that gets the st dev
print("The variance is:",gradebook.variance()) # calling the method that gets the variance

'''
10 Points - Why would you need each of these statistics?
• mean - to give us a clear indication on how well the class is doing on average. If the average is low, the teacher
may look to alter their methods of teaching in order to improve the class average.
• median - The median gives us the centre of the dataset. This would be useful to know because when we compare the 
median to the mean, we can find out about the distribution of the dataset. If the median and mean are similar, we can
say that the data set is fairly evenly distributed.
• mode (you may apply a floor or rounding function to it to allow for groupings) - The mode gives us the most common result.
This is probably the least useful statistic for this particular classroom example, because a mode is at it's most useful
when used upon non mathematical data. The mode here could give us an idea of the central tendency of the data however.
• standard deviation - The standard deviation is useful because it tells us how far on average the data deviates from the mean.
A smaller standard deviation would mean we had less high highs and less low lows, and a more dense amount of data close to our mean.
• variance - The variance also tells us the spread of the data, and the larger the variance in relation to the mean,
the more spread the data. Variance is st.dev squared.
'''